rds_token_path: ~/.ssh/schlafdata/rds.env
dns_domain: schlafdata.cloud
vault_addr: https://vault.schlafdata.cloud
git_public_key_path: ~/.ssh/schlafdata/id_ed25519_git.pub
git_private_key_path: ~/.ssh/schlafdata/id_ed25519_git
vault_key_path: ~/.ssh/schlafdata/vault_init_output.json
rds_username: schlafdata_rds_admin
rds_instance_hostname: schlafdata-app-dev-db.cgczspewjg6d.us-west-2.rds.amazonaws.com:5432
