networkCIDR: 174.64.0.0/16
networkID: vpc-0b5087f6bdafd0497
natGatewayId: nat-0f9f0b334798c9fc5
iamPolicyArns:
  efs-csi-controller-sa: arn:aws:iam::406622241617:policy/efs-csi-controller-sa
  aws-lb-controller: arn:aws:iam::406622241617:policy/aws-lb-controller
  ecr: arn:aws:iam::406622241617:policy/ecr
  kops: arn:aws:iam::406622241617:policy/kops
  external-dns: arn:aws:iam::406622241617:policy/external-dns
  efs-access-point-policy: arn:aws:iam::406622241617:policy/efs-access-point-policy
privateSubnets:
- availability_zone: us-west-2a
  subnet_id: subnet-0d40e2efbf64ff3e5
  subnet_cidr: 174.64.10.0/27
- availability_zone: us-west-2b
  subnet_id: subnet-0e40cf1b941ae1a15
  subnet_cidr: 174.64.10.32/27
- availability_zone: us-west-2c
  subnet_id: subnet-0bbfb59f99e5fe7df
  subnet_cidr: 174.64.10.64/27
- availability_zone: us-west-2d
  subnet_id: subnet-0a2db2a7865606f5c
  subnet_cidr: 174.64.10.96/27
publicSubnets:
- availability_zone: us-west-2a
  subnet_id: subnet-05268c0edf1653894
  subnet_cidr: 174.64.1.0/27
- availability_zone: us-west-2b
  subnet_id: subnet-0f0ac14021f953270
  subnet_cidr: 174.64.1.32/27
- availability_zone: us-west-2c
  subnet_id: subnet-02dd7628aea17ea8d
  subnet_cidr: 174.64.1.64/27
- availability_zone: us-west-2d
  subnet_id: subnet-0bec9f9e195635fa8
  subnet_cidr: 174.64.1.96/27
kops_ssh_key_name: id_ed25519_kops
awsRegion: us-west-2
projectName: schlafdata
dnsZone: schlafdata
dnsDomain: schlafdata.cloud
dnsZoneId: Z073043915ZSR6Y60ZWLQ
vpnInternalNetworkIp: 10.8.0.0/24
machineType: m5.large
maxNodeSize: 3
image: ami-01b22a09b36812401
gpuGroups:
- machineType: g4dn.xlarge
  igName: g4dn-xl
  maxNodeSize: 1
  gpus: 1
additionalDnsZones:
- Z0874785XIHL4I3XGPM9
- Z0612241TJCICYF5G5HV
- Z05003623RKSQ1Y4SUJJ9
additionalGpuNodeGroups:
- machineType: g4dn.2xlarge
  igName: g4dn-2xl
  maxNodeSize: 1
  gpus: 1
- machineType: g4dn.4xlarge
  igName: g4dn-4xl
  maxNodeSize: 1
  gpus: 1
- machineType: g4dn.12xlarge
  igName: g4dn-12xl
  maxNodeSize: 1
  gpus: 4
- machineType: g5.xlarge
  igName: g5-xl
  maxNodeSize: 1
  gpus: 1
- machineType: g5.4xlarge
  igName: g5-4xl
  maxNodeSize: 1
  gpus: 1
- machineType: g5.12xlarge
  igName: g5-12xl
  maxNodeSize: 1
  gpus: 4
kopsStateStore: kops-dev.schlafdata.cloud
clusterName: k8s-dev.schlafdata.cloud
discoveryStore: iam-http-dir-dev-schlafdata-cloud
environment: dev
