development:
  values_file: sub_charts/development/values.yaml
  tmpl_file: mage-workspace.tmpl.yaml
  ingress_class_name: nginx-internal
  workspace_name: development
  web_alias: dev
  gitBranch: dev
  dbtEnv: "__$DEV"
  sa_name: efs-csi-controller-sa
  port: '6789'
  name: mageai-dev-wkspc
  path: /development
  vars:
  - dnsDomain
  - tlsSecretName
  - efsVolumeHandle
  - awsRegion
  - gitAdminEmail
  - gitAdminUsername
  - mageGitRepoLink
