image:
  repository: {{ awsEfsDriver }}
controller:
  serviceAccount:
    create: true
    name: {{ service_account_name }}
    annotations:
      iam.amazonaws.com/role: {{ iam_role }}

storageClasses:
- name: efs-dynamic-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
    provisioningMode: efs-ap
    fileSystemId: {{ efsVolumeHandle }}
    directoryPerms: "700"
    gidRangeStart: "1000"
    gidRangeEnd: "2000"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate