image:
  repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
controller:
  serviceAccount:
    create: true
    name: efs-csi-controller-sa
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::406622241617:policy/efs-csi-controller-sa
storageClasses:
- name: efs-dynamic-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  parameters:
    provisioningMode: efs-ap
    fileSystemId: fs-026bbad7fecf19426
    directoryPerms: '700'
    gidRangeStart: '1000'
    gidRangeEnd: '2000'
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
