apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::406622241617:policy/efs-csi-controller-sa
    meta.helm.sh/release-name: aws-efs-csi-driver
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-controller-sa
  namespace: default