inputs:
  output_path: ./{environment}/k8s/helm/input_configs/helm_generated_config.yml
  variables:
  - source_path: ./{environment}/global_settings.yml
    awsRegion: .aws_region
    projectName: .project_name
    dnsDomain: .dns.dns_domain
    gitAdminEmail: .git_admin_email
    gitAdminUsername: .git_admin_username
    mageGitRepoLink: .mage_git_repo_link
    awsEfsDriver: .aws_efs_driver
  - source_path: ./{environment}/aws_base_outputs.yml
    efsVolumeHandle: .efs_id
    rdsInstanceHostname: .rds_instance_hostname
    rdsUsername: .rds_username
    efsAccessPointArn: .efs_access_point_arn
    efsArn: .efs_arn
    iamPolicyArns: .iam_policy_arns
    rdsInstanceHostNoPort: .rds_instance_host_no_port
