apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-app
  template:
    metadata:
      labels:
        app: gpu-app
    spec: 
      runtimeClassName: nvidia
      containers:
      - name: cuda-container
        image: nvidia/cuda:12.3.2-base-ubuntu22.04
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        resources: 
          limits: 
            nvidia.com/gpu: 1 
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      nodeSelector:
        instance-group: 'gpu-nodes-g4dn-xl'
