name: {{ name }}

ingress_class_name: {{ ingress_class_name }}
ingress:
  domain_dns: {{ dnsDomain }}
  tls_secret: {{ tlsSecretName }}
  service_name: {{ name }}


### storage values

storage:
  storageClassName: 'efs-dynamic-sc'
  storage: {{ persistenceSize }}
  volume_handle: {{ efsVolumeHandle }}
  access_mode: ReadWriteOnce
  aws_role: {{ iam_role }}

deployment:
  image: {{ image }}
  env:
    DEFAULT_MODEL_HG_REPO_ID: {{ DEFAULT_MODEL_HG_REPO_ID }}
    DEFAULT_MODEL_FILE: {{ DEFAULT_MODEL_FILE }}
    GPU_LAYERS: {{ GPU_LAYERS }}

resources:
  limits:
    nvidia.com/gpu: 1

model:
  persistence:
    size: {{ persistenceSize }}
    accessModes:
      - ReadWriteOnce
    storageClassName: 'efs-dynamic-sc'

service:
  type: NodePort
  port: 8000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"

nodeSelector:
  instance-group: "gpu-nodes-g4dn-xl"
tolerations:
- effect: NoSchedule
  key: nvidia.com/gpu
  operator: Exists

affinity: {}