modules:
  global_settings: 
    source_config_path: ./global_settings.yml
    template_path: ./{environment}/templates/global_settings.tmpl.j2
    output_path: ./{environment}/global_settings.yml
  aws_base_outputs: 
    source_config_path: ./{environment}/terraform/aws_base/generated/module_outputs.json
    render_funcs: 
    - get_iam_policy_arns
    - get_subnet_values
    template_path: ./{environment}/templates/aws_base_outputs.tmpl.j2
    output_path: ./{environment}/aws_base_outputs.yml
  kops_base_configs: 
    source_config_path: ./{environment}/kops/input_configs/current_generated_config.yml
    template_path: ./{environment}/templates/kops_custom_settings.tmpl.j2
    output_path: ./{environment}/kops/input_configs/kops_base_configs.yml
    render_funcs:
    - kops_iam_policies
    - compact_subnets
    - defaultdict_to_dict
  helm_base_configs:
    source_config_path: ./{environment}/k8s/helm/input_configs/helm_generated_config.yml
    template_path: ./{environment}/templates/helm_chart_values.tmpl.j2
    output_path: ./{environment}/k8s/helm/input_configs/helm_base_configs.yml   
  mage_rbac_configs:
    source_config_path: ./{environment}/rbac/input_configs/mage_generated_config.yml
    template_path: ./{environment}/templates/mage_rbac_mgmt.j2
    output_path: ./{environment}/rbac/input_configs/mage_rbac_configs.yml    